export const GROUP_LIMITS = {
  USER: {
    POSTS_PER_HOUR: 5,
    COMMENTS_PER_HOUR: 20,
    LIKES_PER_HOUR: 30,
    MAX_UPLOAD_SIZE_MB: 10
  },
  DONATOR: {
    POSTS_PER_HOUR: 10,
    COMMENTS_PER_HOUR: 50,
    LIKES_PER_HOUR: 100,
    MAX_UPLOAD_SIZE_MB: 25
  }
};
